//====================================================
// File: MotorDriverCommand.hpp
//====================================================

#pragma once

#include "../driver/MotorDriverTypes.hpp"

#include <stdint.h>

//====================================================
// MotorDriverCommand
// Low-level hardware-neutral motor command.
// Generated by: MotorController
// Consumed by: IMotorDriver
//====================================================

struct MotorDriverCommand
{
    // Motor channel
    MotorChannel channel = MotorChannel::Left;

    // Direction
    MotorDirection direction = MotorDirection::Stop;

    // Normalized PWM percentage: Range: 0.0 -> 1.0
    // Hardware driver converts: percentage -> hardware PWM resolution
    // MotorController fully hardware-independent
    float pwmPercent = 0.0f;

    // Brake mode
    BrakeMode brakeMode = BrakeMode::Coast;

    // Motor enabled
    bool enabled = true;

    // Emergency command
    bool emergencyStop = false;

    // Sequence identifier: Useful for: debugging, synchronization, telemetry
    uint32_t sequenceId = 0;

    // Timestamp
    uint32_t timestampMs = 0;
};