//====================================================
// File: WheelCommand.hpp
//====================================================

#pragma once

#include "../driver/MotorDriverTypes.hpp"

#include <stdint.h>

//====================================================
// WheelCommand
// Single wheel execution target.
// Generated by:
//      MotorController
// Consumed by:
//      IMotorDriver

struct WheelCommand
{
    // Wheel speed percentage: Range: 0.0 -> 1.0
    float speedPercent = 0.0f;

    //-----------------------------------------
    // Direction
    //-----------------------------------------

    MotorDirection direction =
        MotorDirection::Stop;

    //-----------------------------------------
    // Brake mode
    //-----------------------------------------

    BrakeMode brakeMode =
        BrakeMode::Coast;

    //-----------------------------------------
    // Emergency brake request
    //-----------------------------------------

    bool emergencyBrake = false;

    //-----------------------------------------
    // Wheel enabled
    //-----------------------------------------

    bool enabled = true;

    //-----------------------------------------
    // Timestamp
    //-----------------------------------------

    uint32_t timestampMs = 0;
};