; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf

monitor_speed = 115200
build_type = debug

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17

    ; Shared
    -Ilib/shared
    -Ilib/shared/core
    -Ilib/shared/interfaces
    -Ilib/shared/utilities

    ; ESP32 platform
    -Ilib/platform_esp32

build_src_flags =
    -Wno-unused-variable
    -Wno-unused-parameter
    -Wno-missing-field-initializers

# Very Imp for MonoRepo
lib_ldf_mode = deep+

lib_compat_mode = strict


